using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace GoldMeridian.KeyGen.Utilities;

internal static class Extensions
{
    private const string embedded_attribute_definition =
        """
        // <auto-generated/>
        namespace Microsoft.CodeAnalysis
        {
            internal sealed partial class EmbeddedAttribute : global::System.Attribute
            {
            }
        }
        """;

    extension(IncrementalGeneratorPostInitializationContext ctx)
    {
        // Takes advantage of the fact modern versions of the compiler will
        // enforce partiality.  We're stuck on an older verison of the compiler
        // for compatibility purposes with other workflows, but we can still
        // mirror this implementation.
        // This only works for C#.
        // https://github.com/dotnet/roslyn/blob/5dd606bb21208dfc6fd3d9b07ae963a93248483b/src/Compilers/Core/Portable/SourceGeneration/IncrementalContexts.cs#L225
        public void PolyfillAddEmbeddedAttributeDefinition()
        {
            ctx.AddSource(
                "Microsoft.CodeAnalysis.EmbeddedAttribute",
                SourceText.From(embedded_attribute_definition, Encoding.UTF8)
            );
        }
    }
}
